app/routes/company/routes.py
from flask import Blueprint, request, render_template, session, redirect, send_from_directory, current_app
import os
import time
from ...config import *
from ...db_functions import *
from mysql.connector import *
import locale

company = Blueprint('company', __name__, template_folder='templates')


@company.route('/company')
def company_menu ():

    if not session:
        return redirect('/login')
    if session.get('adm') == True:
        return redirect('/admin')

    company = session['companyInfo']

    try:

        connection, cursor = DB.connect()
        cursor.execute("SELECT * FROM vacancy WHERE companyID = %s AND status = 'active' ORDER BY vacancyID DESC", (company['companyID'],))
        activeVacancies = cursor.fetchall()

        cursor.execute("SELECT * FROM vacancy WHERE companyID = %s AND status = 'inactive' ORDER BY vacancyID DESC", (company['companyID'],))
        inactiveVacancies = cursor.fetchall()

        locale.setlocale(locale.LC_ALL, 'pt-BR.UTF-8')

        for vacancy in activeVacancies:
            salary = float(vacancy['salary'])
            salary = locale.currency(salary, grouping=True)
            vacancy['salary'] = salary

        for vacancy in inactiveVacancies:
            salary = float(vacancy['salary'])
            salary = locale.currency(salary, grouping=True)
            vacancy['salary'] = salary

    except Exception as e:
        print(f'Backend Error: {e}')

    except Error as e:
        print(f'DB Error: {e}')

    finally:       

        DB.stop(connection, cursor)

    return render_template('company.html', company=company, activeVacancies=activeVacancies, inactiveVacancies=inactiveVacancies)


@company.route('/new-vacancy', methods=['GET', 'POST'])
def new_vancancy ():

    if session.get('adm') == True:
        return redirect('/login')

    elif request.method == 'GET':
        return render_template('new-vacancy.html')

    elif request.method == 'POST':
        
        company = session['companyInfo']
        companyID = company['companyID']
        vacancyTitle = request.form['title']
        vacancyDescription = request.form['description']
        vacancyArrangement = request.form['arrangement']
        vacancyType = request.form['type']
        vacancyLocation = request.form['location']
        vacancySalary = DB.clearInput('currency', (request.form['salary']))

        if not vacancyTitle or not vacancyDescription or not vacancyArrangement or not vacancyType or not vacancyLocation or not companyID or not vacancySalary:
            return render_template('new-vacancy.html', errormsg='Todos os campos são obrigatórios!')
        
        try:
            connection, cursor = DB.connect()

            SQLstatement = '''
            INSERT INTO vacancy VALUES
            (null, %s, %s, %s, %s, %s, %s, %s, 'active') ;'''

            cursor.execute(SQLstatement, (vacancyTitle, vacancyDescription, vacancyArrangement, vacancyType, vacancyLocation, vacancySalary, companyID))
            connection.commit()

        except Exception as e:
            print(f'Error: {e}')
    
        finally:
            DB.stop(connection, cursor)
        
        return redirect('/company')

# VACANCY EDITING ROUTE

@company.route('/edit-vacancy/<int:id>', methods=['GET', 'POST'])
def edit_vacancy (id):

    if session.get('adm') == True:
        return redirect('/adm')

    elif request.method == 'GET':

        try:
            connection, cursor = DB.connect()

            cursor.execute(f'SELECT * FROM vacancy WHERE vacancyID = {id} ;')
            vacancy = cursor.fetchone()

            company = session['companyInfo']

            if company['companyID'] != vacancy['companyID']:
                return redirect('/company')

        except Exception as e:
            print(f'Back-End Error: {e}')
    
        except Error as e:
            print(f"DB Error: {e}")
    
        finally:

            DB.stop(connection, cursor)
    
        return render_template('edit-vacancy.html', vacancy=vacancy, id=id)

    elif request.method == 'POST':

        vacancyTitle = request.form['title']
        vacancyDescription = request.form['description']
        vacancyArrangement = request.form['arrangement']
        vacancyType = request.form['type']
        vacancyLocation = request.form['location']
        vacancySalary = DB.clearInput('currency', (request.form['salary']))

        if not vacancyTitle or not vacancyDescription or not vacancyArrangement or not vacancyType or not vacancyLocation or not vacancySalary:
            return render_template('edit-vacancy.html', errormsg='All fields are obrigatory!')
        
        try:
            connection, cursor = DB.connect()

            SQLstatement = '''
            UPDATE vacancy
            SET title = %s,
            description = %s,
            arrangement = %s,
            type = %s,
            location = %s,
            salary = %s
            WHERE vacancyID = %s;'''

            cursor.execute(SQLstatement, (vacancyTitle, vacancyDescription, vacancyArrangement, vacancyType, vacancyLocation, vacancySalary, id))
            connection.commit()

        except Exception as e:
            print(f'Error: {e}')
    
        finally:
            DB.stop(connection, cursor)
        
        return redirect('/company')

# VACANCY STATUS SWITCHING ROUTE

@company.route('/switch-vacancy-status/<int:id>')
def switch_vacancy_status (id):
    
    if session.get('adm') == True:
        return redirect('/admin')
    
    elif not session['companyInfo']:
        return redirect('/login')

    try:


        connection, cursor = DB.connect()
        cursor.execute('''SELECT * FROM vacancy WHERE vacancyID = %s ;''', (id,))
        vacancy = cursor.fetchone()
        
        company = session['companyInfo']

        if vacancy['companyID'] != company['companyID']:
            return redirect('/company')

        elif vacancy['status'] == 'active':

            cursor.execute('''UPDATE vacancy
                SET status = 'inactive' 
                WHERE vacancyID = %s ;''', (id,))

        elif vacancy['status'] == 'inactive':
            
            cursor.execute('''UPDATE vacancy
                SET status = 'active' 
                WHERE vacancyID = %s ;''', (id,))

    except Exception as e:
        print(f'Back-End Error: {e}')

    except Error as e:
        print(f"DB Error: {e}")
        
    finally:
        connection.commit()
        DB.stop(connection, cursor)

    return redirect('/company')

# VACANCY DELETION ROUTE

@company.route('/delete-vacancy/<int:id>')
def delete_vacancy (id):
    
    if session.get('adm') == True:
        return redirect('/admin')

    try:
        connection, cursor = DB.connect()

        cursor.execute('''SELECT * FROM vacancy WHERE vacancyID = %s ;''', (id,))

        vacancy = cursor.fetchone()
        company = session['companyInfo']

        if vacancy['companyID'] != company['companyID']:
            return redirect('/company')
            
        else:

            cursor.execute('SELECT fileName FROM apply WHERE vacancyID = %s', (id,))
            files = cursor.fetchall()

            for file in files:
                os.remove(f'{current_app.config['UPLOAD_FOLDER']}{file['fileName']}')

            cursor.execute('''DELETE FROM vacancy WHERE vacancyID = %s ;''', (id,))        

    except Exception as e:
        print(f'Back-End Error: {e}')

    except Error as e:
        print(f"DB Error: {e}")
        
    finally:
        connection.commit()
        DB.stop(connection, cursor)
    
    return redirect('/company')

@company.route('/vacancy-docs/<int:id>')
def vacancy_docs(id):
    try:
        connection, cursor = DB.connect()
        cursor.execute('SELECT * FROM vacancy WHERE vacancyID = %s', (id,))
        vacancy = cursor.fetchone()
        cursor.execute('SELECT * FROM apply WHERE vacancyID = %s', (id,))
        files = cursor.fetchall()

    except Error as e:
        print(f"DB Error: {e}")
        return f"DB Error: {e}", 500
    except Exception as e:
        print(f"Back-end Error: {e}")
        return f"Back-end Error: {e}", 500
    finally:
        DB.stop(connection, cursor)

    return render_template('vacancy-applies.html', files=files, vacancy=vacancy)

@company.route('/download/<int:id>')
def download(id):

    if not session:
        return redirect('/login')

    try:

        connection, cursor = DB.connect()

        cursor.execute('''SELECT companyID FROM vacancy WHERE vacancyID = (SELECT vacancyID FROM apply WHERE applyID = %s);''', (id,))
        companyID = cursor.fetchone()

        company = session['companyInfo']

        if companyID['companyID'] != company['companyID']:
            redirect('/company')

        cursor.execute('''SELECT fileName FROM apply WHERE applyID = %s ;''', (id,))
        filename = cursor.fetchone()

        if not filename:
            return redirect('/') 

        filename = filename['fileName']  
        file_path = os.path.join(current_app.config['UPLOAD_FOLDER'], filename)

        if not os.path.exists(file_path):
            return "File not found on server", 404


        return send_from_directory(f"{os.getcwd()}/app/uploads/", filename, as_attachment=False)


    except mysql.connector.Error as db_error:  # Catch specific database errors
        print(f"Database Error: {db_error}")
        return f"Database Error: {db_error}", 500
    
    except FileNotFoundError as fnf_error:  #Catch file not found errors
        print(f"File Not Found: {fnf_error}")
        return f"File Not Found: {fnf_error}", 404
    
    except Exception as e:  #Catch other unexpected errors
        print(f"Unexpected Error: {e}")
        return redirect('/company')

    finally:
        DB.stop(connection, cursor)


@company.route('/delete-file/<int:id>')
def delete_file(id):
    try:
        connection, cursor = DB.connect()
        cursor.execute('''SELECT fileName, vacancyID FROM apply WHERE applyID = %s;''', (id,))

app/routes/company/templates/components/c-apply-card.html
<div class="card h-100" style="min-height: 27rem;">
    <div class="card-body d-flex justify-content-between flex-column">
        <h5 class="card-title text-start">
            <strong>{{ file.name }}</strong>
        </h5>
        <p class="card-text text-start fs-6 opacity-75">
            <strong>ID da Candidatura:</strong> {{ file.applyID }} <br>
            <strong>E-mail:</strong> {{ file.email }} <br>
            <strong>Telefone:</strong> {{ file.phone }}
        </p>

        <div class="col-12 opacity-50 text-center text-md-start text-lg-start text-wrap">
            Arquivo: {{ file.fileName }}
        </div>

        <div class="row g-2 d-flex mt-3 justify-content-center">
            <a class="p-2 rounded-5 border border-1 btn btn-primary m-1 col-12" 
                href="{{ url_for('company.download', id=file.applyID) }}" 
                target="_blank">
                Download
            </a>
            <a class="p-2 rounded-5 border border-1 btn btn-danger m-1 col-12" 
                href="/delete-file/{{ file.applyID }}" 
                onclick="return confirm('Tem certeza que deseja excluir este arquivo?')">
                Excluir
            </a>
        </div>
    </div>
    <div class="card-footer text-muted">
        <strong>Data:</strong> {{ file.date }}
    </div>
</div>

app/routes/company/templates/components/c-vacancy-card.html
<div class="card h-100">
    <div class="card-body d-flex justify-content-between flex-column">
        <h5 class="card-title text-start"><strong>{{ vacancy.title }}</strong></h5>
        <p class="card-text text-start fs-6 opacity-75">{{ vacancy.description }}</p>
    
        <p class="col-12 opacity-50 text-center text-md-start text-lg-start text-nowrap">
            ID: {{ vacancy['vacancyID'] }} • {{ vacancy.type }} • 
            {% if vacancy.arrangement == 'Remote' %}Remoto{% elif vacancy.arrangement == 'Hybrid' %}Híbrido{% else %}Presencial{% endif %}
        </p>
    
        <div class="col-12 opacity-75 mb-3 text-md-start text-lg-start text-center text-nowrap">
            <i class="bi bi-geo-alt-fill me-1"></i>{{ vacancy.location }}
        </div>
    
        <div class="row g-2 d-flex mt-3 justify-content-center">
            <a class="p-2 rounded-5 border border-1 btn btn-primary m-1 col-12" href="/vacancy-docs/{{ vacancy['vacancyID'] }}">Candidaturas</a>
            <a class="p-2 rounded-5 border border-1 btn btn-primary m-1 col-12" href="/edit-vacancy/{{ vacancy['vacancyID'] }}">Editar</a>
            {% if vacancy.status == 'active' %}
            <a class="p-2 rounded-5 border border-1 btn btn-warning m-1 text-nowrap col-12" onclick="confirm('Tem certeza de que quer desativar esta vaga?')" href="/switch-vacancy-status/{{ vacancy['vacancyID'] }}">
                Desativar
            </a>
            {% else %}
            <a class="p-2 rounded-5 border border-1 btn btn-warning m-1 text-nowrap col-12" onclick="confirm('Tem certeza de que quer desativar esta vaga?')" href="/switch-vacancy-status/{{ vacancy['vacancyID'] }}">
                Ativar
            </a>
            <a class="p-2 rounded-5 border border-1 btn btn-danger m-1 col-12" href="/delete-vacancy/{{ vacancy['vacancyID'] }}" onclick="confirm('Tem certeza que deseja excluir esta vaga?')">Excluir</a>
            {% endif %}
        </div>        
    </div>
    <div class="card-footer text-muted" id="salary">{{ vacancy.salary }}</div>
</div>